// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjdLtzUogHDXawLbq9AAarze2hvRgl7bU',
    appId: '1:447469522838:web:c0869f02d4159b5dc8d7b7',
    messagingSenderId: '447469522838',
    projectId: 'vibechat-9a0c0',
    authDomain: 'vibechat-9a0c0.firebaseapp.com',
    storageBucket: 'vibechat-9a0c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4OTIV1nGz54IxaGEkpzT_BfiBIFWIv9E',
    appId: '1:447469522838:android:43ecaeeeaeb80b86c8d7b7',
    messagingSenderId: '447469522838',
    projectId: 'vibechat-9a0c0',
    storageBucket: 'vibechat-9a0c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvuS8OOXYfiKNchTYo_UTNvaMeX6rWNTk',
    appId: '1:447469522838:ios:5c3451268e856619c8d7b7',
    messagingSenderId: '447469522838',
    projectId: 'vibechat-9a0c0',
    storageBucket: 'vibechat-9a0c0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvuS8OOXYfiKNchTYo_UTNvaMeX6rWNTk',
    appId: '1:447469522838:ios:5c3451268e856619c8d7b7',
    messagingSenderId: '447469522838',
    projectId: 'vibechat-9a0c0',
    storageBucket: 'vibechat-9a0c0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjdLtzUogHDXawLbq9AAarze2hvRgl7bU',
    appId: '1:447469522838:web:e9fcb30f7a951de3c8d7b7',
    messagingSenderId: '447469522838',
    projectId: 'vibechat-9a0c0',
    authDomain: 'vibechat-9a0c0.firebaseapp.com',
    storageBucket: 'vibechat-9a0c0.firebasestorage.app',
  );
}
